name: ble_beacon_scanner
description: Aplicativo Flutter para detectar beacons BLE ESP32

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.0.2
  permission_handler: ^11.0.1
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  flutter_tts: ^3.8.2
  http: ^0.13.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
